# -*- coding: utf-8 -*-
"""經濟二乙 A107260028 張雅筑

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2OvjZIGuNt1N_zPhCAk9KyZaFbtBSfV
"""

print("Hello World!")

import this