# -*- coding: utf-8 -*-
"""經濟二乙 A107260028 張雅筑

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XGSQ__2lbAUIPyVLwqrQaCGU5tL9IKE5
"""

movie_title ="Avengers: Endgame"
movie_time =181
movie_rating =8.4

print(movie_time)
print(movie_rating)
print(movie_title)

print(type(movie_time))
print(type(movie_rating))
print(type(movie_title))